### ISSUE TITLE
Remove bomb from map

### ISSUE THREAD

**Issue by Bobakanoosh** [Keplyx/chickenwars#3]
If I wish to play on a de_ map it would be nice to have the bomb auto-removed :p (pretty sure there's no setting for this).

**Comment by Keplyx** [comment]
there's a cvar for that: mp_give_player_C4 0. I'm not forcing c4 removing in case someone wants to play a defuse match as a chicken

**Comment by Bobakanoosh** [comment]
Could just make it as part of the config ;p
thanks for that cvar :)

**Comment by Keplyx** [comment]
"mp_give_player_C4 0" is now in the config file
